project:
  type: book
book:    
  author: "Akeem Semper"
  date: "01-Jan-2023"
  title: "Intro to Machine Learning"


number-sections: false
jupyter: python3
execute: 
  enabled: true

format:
  html:
    output-dir: _output_HTML
    css: styles.css
    html-math-method: katex
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-fold: true
    execute: 
      enabled: true
      echo: false
    anchor-sections: true
    smooth-scroll: true
  pdf:
    output-dir: _output_PDF
    documentclass: scrreport
    toc: false
  docx:
    output-dir: _output_DOCX
    highlight-style: github
    toc: false
